// iconUtils.ts
import {
  FaPiggyBank,
  FaGift,
  FaShieldAlt,
  FaMoneyCheckAlt,
  FaLightbulb,
  FaBuilding,
  FaFileAlt,
  FaBalanceScale,
  FaGavel,
  FaHandHoldingUsd,
  FaUsers,
  FaPalette,
  FaChartBar,
  FaFileInvoiceDollar,
  FaLightbulb as FaIdea,
  FaHandshake,
  FaServer,
  FaUserAstronaut,
  FaCode,
  FaBullhorn,
  FaPaintBrush,
  FaChartLine,
  FaCog,
  FaShoppingBag,
  FaTrademark,
  FaUserFriends,
  FaAward,
  FaHandsHelping,
  FaUsers as FaCommunity,
  FaLeaf,
  FaHands,
  FaHeart,
  FaCrown,
  FaBriefcase,
  FaUmbrella
} from "react-icons/fa";

export const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  FaPiggyBank,
  FaGift,
  FaShieldAlt,
  FaMoneyCheckAlt,
  FaLightbulb,
  FaBuilding,
  FaFileAlt,
  FaBalanceScale,
  FaGavel,
  FaHandHoldingUsd,
  FaUsers,
  FaPalette,
  FaChartBar,
  FaFileInvoiceDollar,
  FaIdea,
  FaHandshake,
  FaServer,
  FaUserAstronaut,
  FaCode,
  FaBullhorn,
  FaPaintBrush,
  FaChartLine,
  FaCog,
  FaShoppingBag,
  FaTrademark,
  FaUserFriends,
  FaAward,
  FaHandsHelping,
  FaCommunity,
  FaLeaf,
  FaHands,
  FaHeart,
  FaCrown,
  FaBriefcase,
  FaUmbrella
};

export const getIconComponent = (iconName: string): React.ComponentType<{ className?: string }> => {
  return iconMap[iconName] || FaBuilding; 
};